name: Potato Api Backend

on:
  push:
    branches: [ "backend" ]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          cd potato-api
          chmod +x mvnw
          ./mvnw test

      - name: Create .env file for Docker Compose
        run: |
          echo "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" >> .env
          echo "APP_SERVER_URL=${{ secrets.APP_SERVER_URL }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env

          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env

          echo "VNPAY_SECRET_KEY=${{ secrets.VNPAY_SECRET_KEY }}" >> .env

      - name: remove old images and clear memory
        run: |
          docker image prune -af || true

      - name: Down all container
        run: |
          docker compose down

      - name: Build & start new containers
        run: |
          docker compose up -d --build
      


